-- Create gmi_weekly table based on gmi_monthly structure
-- Using gmw_ prefix as discussed

CREATE TABLE `gmi_weekly` (
  `gmw_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `site_id` smallint(6) DEFAULT NULL,
  `gmw_year` smallint(6) DEFAULT NULL,
  `gmw_week` tinyint(4) DEFAULT NULL,
  `gmw_ppm_tier_name` varchar(20) DEFAULT NULL,
  `gmw_ppm_tier_point` decimal(3,1) DEFAULT NULL,
  `gmw_ppm_total` smallint(6) DEFAULT NULL,
  `gmw_ppm_completed` smallint(6) DEFAULT NULL,
  `gmw_ppm_on_time` smallint(6) DEFAULT NULL,
  `gmw_ppm_late` smallint(6) DEFAULT NULL,
  `gmw_ppm_within` smallint(6) DEFAULT NULL,
  `gmw_ppm_rework` smallint(6) DEFAULT NULL,
  `gmw_ppm_assist` smallint(6) DEFAULT NULL,
  `gmw_wo_tier_name` varchar(20) DEFAULT NULL,
  `gmw_wo_tier_point` decimal(3,1) DEFAULT NULL,
  `gmw_wo_total` smallint(6) DEFAULT NULL,
  `gmw_wo_completed` smallint(6) DEFAULT NULL,
  `gmw_wo_on_time` smallint(6) DEFAULT NULL,
  `gmw_wo_late` smallint(6) DEFAULT NULL,
  `gmw_wo_rework` smallint(6) DEFAULT NULL,
  `gmw_wo_self_finding` smallint(6) DEFAULT NULL,
  `gmw_wo_assist` smallint(6) DEFAULT NULL,
  `gmw_mbv` smallint(6) DEFAULT NULL,
  `gmw_tier_point` tinyint(1) DEFAULT NULL,
  `gmw_point_completed` int(11) DEFAULT NULL,
  `gmw_point_on_time` int(11) DEFAULT NULL,
  `gmw_point_late` int(11) DEFAULT NULL,
  `gmw_point_rework` int(11) DEFAULT NULL,
  `gmw_point_self_finding` int(11) DEFAULT NULL,
  `gmw_point_total` int(11) DEFAULT NULL,
  `gmw_productivity_level` decimal(6,2) DEFAULT NULL,
  `gmw_productivity_deduction` decimal(6,2) DEFAULT NULL,
  `gmw_point_less_productive` int(11) DEFAULT NULL,
  `gmw_point_before_minus` int(11) DEFAULT NULL,
  `gmw_point_after_minus` int(11) DEFAULT NULL,
  PRIMARY KEY (`gmw_id`),
  KEY `user_id` (`user_id`),
  KEY `site_id` (`site_id`),
  UNIQUE KEY `unique_weekly` (`user_id`, `site_id`, `gmw_year`, `gmw_week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
