-- ============================================================================
-- SYNC WORK ORDER WORKFLOW: gfm_jkr  ->  match gems (Global)
-- ============================================================================
-- Purpose : Make the Work Order workflow CONFIGURATION in the JKR database
--           (gfm_jkr @ localhost) identical to gems Global
--           (gems @ www.metadatasystem.my), which is the source of truth.
--
-- Scope   : Work Order flow ONLY  ->  wfl_flow.flow_id = 2 ("Work Order")
--           (Material Request / flow_id = 4 differences are OUT OF SCOPE here;
--            see maintenance/prod_sync_mr_workflow.sql for that flow.)
--
-- Generated by comparing the two live databases on 2026-05-29 (READ-ONLY).
--
-- WORKFLOW MODEL (how the WO workflow is configured in the DB)
-- ------------------------------------------------------------
--   CONFIGURATION tables (define the flow itself):
--     * wfl_flow             - the flows (PPM, Work Order, PR, MR, FCA)
--     * wfl_checkpoint       - the steps/checkpoints + routing (next / case_1..3)
--     * wfl_checkpoint_assign- pre-assignment rules between checkpoints
--   BRIDGE table (config <-> users; deployment specific):
--     * wfl_checkpoint_user  - which users/groups may act on each checkpoint
--   ACTUAL DATA tables (live transactions, NOT touched by Part A/B/C):
--     * wfl_transaction, wfl_task, wfl_task_assign, wfl_user_report
--
--   The engine (api/function/f_task.php :: submit_task) reads wfl_checkpoint to
--   decide the next step:  next = empty -> checkpoint_next, else checkpoint_case_<n>.
--   wfl_checkpoint_assign rows are read on submit to pre-create wfl_task_assign
--   rows for the next checkpoint (claim_type 3 = "assigned user" REQUIRES one).
--
-- DIFFERENCES FOUND (Global = expected, JKR = current) for flow_id = 2:
-- ------------------------------------------------------------
--   wfl_checkpoint
--     CP 20 "Check WO"   : MISSING in JKR                    -> INSERT (Part A.1)
--     CP 13 "Execute WO" : next 14->20, case_3 NULL->13      -> UPDATE (Part A.2)
--     CP 19 "Verify WR"  : role 6->7, group NULL->1          -> UPDATE (Part A.3)
--   wfl_checkpoint_assign
--     (1,12,20) Assign WO -> Check WO        : MISSING in JKR -> INSERT (Part B.1)
--     (1,17,16) Assign WR -> Verify&Close WO : MISSING in JKR -> INSERT (Part B.1)
--     (1,17,19) Assign WR -> Verify WR       : MISSING in JKR -> INSERT (Part B.1)
--     (1,17,20) Assign WR -> Check WO        : MISSING in JKR -> INSERT (Part B.1)
--     (1,11,19) Submit Complaint -> Verify WR: EXTRA in JKR   -> DELETE (Part B.2)
--                 ^ known bug: pre-assigns the COMPLAINER (role 6) to "Verify WR"
--                   and blocks the real WO Assigner. Global does not have it.
--                   (See maintenance/prod_fix_cp19_assignment.sql.)
--   wfl_checkpoint_user (populated from JKR's OWN users, never copied from Global)
--     CP 20 : needs performers -> copy from JKR CP 12 (role 7)   (Part C.1)
--     CP 19 : needs role-7 performers after role change -> copy from CP 17 (Part C.2)
--
-- IN-FLIGHT IMPACT (already-running WOs) - handled in Part D:
--   New WOs follow the new flow automatically. Existing tickets:
--     * Assign WO (CP12) 4,755 / Assign WR (CP17) 1 : SAFE (assigned on submit)
--     * Execute WO (CP13) type-2 self-finding 2,533  : SAFE (route to CP16, unchanged)
--     * Execute WO (CP13) type-1 normal       93     : need CP20 assignment (Part D.1)
--     * Verify WR (CP19)                       2     : mis-assigned, re-point (Part D.2)
--
-- SAFETY
-- ------------------------------------------------------------
--   * Wrapped in a single transaction; nothing commits until COMMIT at the end.
--   * Idempotent: re-running makes no further changes (guards on every statement).
--   * Schemas are already identical (only a cosmetic utf8 vs utf8mb3 charset
--     alias differs) - NO table/column changes are needed.
--   * Review the verification output (printed at the end) before COMMIT if running
--     interactively. To abort, run ROLLBACK; instead of COMMIT;.
-- ============================================================================

START TRANSACTION;

-- ============================================================================
-- PART A : wfl_checkpoint (configuration)
-- ============================================================================

-- A.1  Add CP 20 "Check WO" (exact values copied from Global). Insert only if missing.
INSERT INTO wfl_checkpoint
  (checkpoint_id, flow_id, checkpoint_desc, checkpoint_type, checkpoint_claim_type,
   checkpoint_due_day, checkpoint_next, checkpoint_case_1, checkpoint_case_2, checkpoint_case_3,
   checkpoint_icon, role_id, group_id, checkpoint_order, checkpoint_color, checkpoint_skip)
SELECT 20, 2, 'Check WO', 2, 3,
       1, 14, 16, 13, NULL,
       'fas fa-check', 7, 1, 5, NULL, b'0'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM wfl_checkpoint WHERE checkpoint_id = 20);

-- A.2  CP 13 "Execute WO": route to Check WO (next=20) and allow return-to-self (case_3=13).
UPDATE wfl_checkpoint
SET checkpoint_next = 20, checkpoint_case_3 = 13
WHERE checkpoint_id = 13 AND flow_id = 2;

-- A.3  CP 19 "Verify WR": owned by WO Assigner (role 7), default group 1 (was role 6 / NULL).
UPDATE wfl_checkpoint
SET role_id = 7, group_id = 1
WHERE checkpoint_id = 19 AND flow_id = 2;

-- ============================================================================
-- PART B : wfl_checkpoint_assign (configuration)
-- ============================================================================

-- B.1  Add the 4 missing pre-assignment rules (type 1 = "assign to himself").
INSERT INTO wfl_checkpoint_assign (checkpoint_assign_type, checkpoint_id, checkpoint_to)
SELECT v.t, v.f, v.o
FROM (
        SELECT 1 AS t, 12 AS f, 20 AS o   -- Assign WO -> Check WO
  UNION SELECT 1,       17,      16        -- Assign WR -> Verify and Close WO
  UNION SELECT 1,       17,      19        -- Assign WR -> Verify WR
  UNION SELECT 1,       17,      20        -- Assign WR -> Check WO
) v
WHERE NOT EXISTS (
  SELECT 1 FROM wfl_checkpoint_assign a
  WHERE a.checkpoint_assign_type = v.t
    AND a.checkpoint_id          = v.f
    AND a.checkpoint_to          = v.o
);

-- B.2  Remove the extra/buggy rule (Submit Complaint -> Verify WR). Global has none.
--      This stops new complaints from pre-assigning the complainer as the WR verifier.
DELETE FROM wfl_checkpoint_assign
WHERE checkpoint_id = 11 AND checkpoint_to = 19;

-- ============================================================================
-- PART C : wfl_checkpoint_user (bridge - uses JKR's OWN users only)
-- ============================================================================
-- These rows are deployment specific (the JKR user base differs from Global), so
-- we DERIVE them from JKR's existing checkpoint-user mappings rather than copying
-- any rows from Global.

-- C.1  Give CP 20 ("Check WO") the same performers as CP 12 ("Assign WO", role 7).
INSERT INTO wfl_checkpoint_user (checkpoint_id, user_id, role_id, group_id)
SELECT 20, cu.user_id, cu.role_id, cu.group_id
FROM wfl_checkpoint_user cu
WHERE cu.checkpoint_id = 12
  AND NOT EXISTS (
    SELECT 1 FROM wfl_checkpoint_user x
    WHERE x.checkpoint_id = 20
      AND x.user_id   = cu.user_id
      AND x.role_id   = cu.role_id
      AND x.group_id  <=> cu.group_id
  );

-- C.2  CP 19 now needs role-7 performers (it changed from role 6). Copy from CP 17.
--      Existing legacy role-6 rows on CP 19 are left in place (harmless; Global also
--      still has legacy role-6 rows on CP 19). To remove them, see the OPTIONAL block.
INSERT INTO wfl_checkpoint_user (checkpoint_id, user_id, role_id, group_id)
SELECT 19, cu.user_id, cu.role_id, cu.group_id
FROM wfl_checkpoint_user cu
WHERE cu.checkpoint_id = 17
  AND NOT EXISTS (
    SELECT 1 FROM wfl_checkpoint_user x
    WHERE x.checkpoint_id = 19
      AND x.user_id   = cu.user_id
      AND x.role_id   = cu.role_id
      AND x.group_id  <=> cu.group_id
  );

-- ----------------------------------------------------------------------------
-- OPTIONAL cleanup (NOT enabled by default). Removes the now-ineffective
-- role-6 performer rows from CP 19. Cosmetic only - the checkpoint role is 7,
-- so role-6 rows can never act. Uncomment to enable.
-- ----------------------------------------------------------------------------
-- DELETE FROM wfl_checkpoint_user WHERE checkpoint_id = 19 AND role_id = 6;

-- ============================================================================
-- PART D : IN-FLIGHT DATA BACKFILL (live wfl_task / wfl_task_assign rows)
-- ----------------------------------------------------------------------------
-- The config change in Parts A/B reroutes WOs that are ALREADY running. Tickets
-- that passed "Assign WO"/"Assign WR" before the new rules existed are missing
-- the downstream assignment and would error (or stay mis-assigned) on submit.
--
-- This part is the JKR equivalent of - and SUPERSEDES -
-- maintenance/prod_fix_cp19_assignment.sql: it covers BOTH the new CP20 gap
-- (93 tickets) AND the CP19 mis-assignment (2 tickets). (prod_fix_cp19 only
-- handled CP19 and re-did the 11->19 delete already done in Part B.2 above, so
-- you do NOT need to run it separately.)
--
-- Counts verified against gfm_jkr on 2026-05-29: 93 CP13(type-1) + 2 CP19.
-- Type-2 self-finding WOs (2,533) and tickets still at Assign WO/WR are NOT
-- touched - they route correctly on their own. Every statement is guarded, so
-- re-running makes no further changes.
-- ============================================================================

-- D.1  Execute WO (CP13) in-flight, type-1 (normal) WOs: create the missing
--      "Check WO" (CP20) assignment they would have received at Assign WO.
--      Assignee is derived from the WO's OWN assigner, in order of reliability:
--        CP16 self-assignment  ->  latest CP12 task  ->  wo_task_assigned_by.
INSERT INTO wfl_task_assign (transaction_id, checkpoint_id, role_id, group_id, user_id)
SELECT s.transaction_id, 20, 7, s.group_id, s.user_id
FROM (
  SELECT t.transaction_id,
    COALESCE(
      (SELECT a.group_id FROM wfl_task_assign a WHERE a.transaction_id=t.transaction_id AND a.checkpoint_id=16 ORDER BY a.task_assign_id DESC LIMIT 1),
      (SELECT c.group_id      FROM wfl_task c WHERE c.transaction_id=t.transaction_id AND c.checkpoint_id=12 ORDER BY c.task_id DESC LIMIT 1),
      t.group_id, 1) AS group_id,
    COALESCE(
      (SELECT a.user_id FROM wfl_task_assign a WHERE a.transaction_id=t.transaction_id AND a.checkpoint_id=16 ORDER BY a.task_assign_id DESC LIMIT 1),
      (SELECT c.task_claimed_user FROM wfl_task c WHERE c.transaction_id=t.transaction_id AND c.checkpoint_id=12 ORDER BY c.task_id DESC LIMIT 1),
      w.wo_task_assigned_by) AS user_id
  FROM wfl_task t
  JOIN wfl_transaction tr ON tr.transaction_id=t.transaction_id AND tr.flow_id=2
  JOIN wo_task w          ON w.transaction_id=t.transaction_id AND w.wo_task_type_init NOT IN ('2','6')
  WHERE t.task_current=1 AND t.checkpoint_id=13
    AND NOT EXISTS (SELECT 1 FROM wfl_task_assign x WHERE x.transaction_id=t.transaction_id AND x.checkpoint_id=20)
) s
WHERE s.user_id IS NOT NULL;

-- D.2a Verify WR (CP19) in-flight: point the live task at the real WO Assigner
--      (taken from CP17) instead of the complainer left by the old 11->19 rule.
UPDATE wfl_task ct
JOIN (
  SELECT x.transaction_id, x.task_claimed_user AS assigner, x.group_id
  FROM wfl_task x
  JOIN (SELECT transaction_id, MAX(task_id) mid FROM wfl_task WHERE checkpoint_id=17 GROUP BY transaction_id) m
    ON m.transaction_id=x.transaction_id AND m.mid=x.task_id
) c17 ON c17.transaction_id=ct.transaction_id
SET ct.task_claimed_user=c17.assigner, ct.group_id=COALESCE(c17.group_id,1), ct.role_id=7
WHERE ct.task_current=1 AND ct.checkpoint_id=19 AND ct.task_status=8
  AND c17.assigner IS NOT NULL
  AND (ct.task_claimed_user IS NULL OR ct.task_claimed_user <> c17.assigner);

-- D.2b ...and its matching assignment row.
UPDATE wfl_task_assign ta
JOIN (
  SELECT x.transaction_id, x.task_claimed_user AS assigner, x.group_id
  FROM wfl_task x
  JOIN (SELECT transaction_id, MAX(task_id) mid FROM wfl_task WHERE checkpoint_id=17 GROUP BY transaction_id) m
    ON m.transaction_id=x.transaction_id AND m.mid=x.task_id
) c17 ON c17.transaction_id=ta.transaction_id
SET ta.user_id=c17.assigner, ta.group_id=COALESCE(c17.group_id,1), ta.role_id=7
WHERE ta.checkpoint_id=19
  AND c17.assigner IS NOT NULL
  AND ta.transaction_id IN (SELECT transaction_id FROM wfl_task WHERE task_current=1 AND checkpoint_id=19 AND task_status=8)
  AND (ta.user_id IS NULL OR ta.user_id <> c17.assigner);

COMMIT;
-- ROLLBACK;  -- <- use this instead of COMMIT to abort after reviewing verification

-- ============================================================================
-- VERIFICATION (run after COMMIT). All checks should report 'OK'.
-- ============================================================================
SELECT 'CP20 exists (Check WO)' AS check_name,
       IF(COUNT(*) = 1, 'OK', 'FAIL') AS result
FROM wfl_checkpoint WHERE checkpoint_id = 20 AND flow_id = 2
UNION ALL
SELECT 'CP13 next=20 & case_3=13',
       IF(COUNT(*) = 1, 'OK', 'FAIL')
FROM wfl_checkpoint WHERE checkpoint_id = 13 AND checkpoint_next = 20 AND checkpoint_case_3 = 13
UNION ALL
SELECT 'CP19 role=7 & group=1',
       IF(COUNT(*) = 1, 'OK', 'FAIL')
FROM wfl_checkpoint WHERE checkpoint_id = 19 AND role_id = 7 AND group_id = 1
UNION ALL
SELECT 'assign rules (12->20,17->16,17->19,17->20) present',
       IF(COUNT(*) = 4, 'OK', CONCAT('FAIL (', COUNT(*), '/4)'))
FROM wfl_checkpoint_assign
WHERE (checkpoint_id, checkpoint_to) IN ((12,20),(17,16),(17,19),(17,20))
UNION ALL
SELECT 'buggy rule (11->19) removed',
       IF(COUNT(*) = 0, 'OK', 'FAIL')
FROM wfl_checkpoint_assign WHERE checkpoint_id = 11 AND checkpoint_to = 19
UNION ALL
SELECT 'CP20 has performers (checkpoint_user)',
       IF(COUNT(*) > 0, 'OK', 'FAIL')
FROM wfl_checkpoint_user WHERE checkpoint_id = 20
UNION ALL
SELECT 'CP19 has role-7 performers (checkpoint_user)',
       IF(COUNT(*) > 0, 'OK', 'FAIL')
FROM wfl_checkpoint_user WHERE checkpoint_id = 19 AND role_id = 7
UNION ALL
SELECT 'in-flight CP13(type-1) all have CP20 assignment',
       IF(COUNT(*) = 0, 'OK', CONCAT('FAIL (', COUNT(*), ' missing)'))
FROM wfl_task t
JOIN wfl_transaction tr ON tr.transaction_id = t.transaction_id AND tr.flow_id = 2
JOIN wo_task w ON w.transaction_id = t.transaction_id AND w.wo_task_type_init NOT IN ('2','6')
WHERE t.task_current = 1 AND t.checkpoint_id = 13
  AND NOT EXISTS (SELECT 1 FROM wfl_task_assign x WHERE x.transaction_id = t.transaction_id AND x.checkpoint_id = 20)
UNION ALL
SELECT 'in-flight CP19 no longer mis-assigned (vs CP17)',
       IF(COUNT(*) = 0, 'OK', CONCAT('FAIL (', COUNT(*), ' mismatched)'))
FROM wfl_task ct
JOIN (SELECT x.transaction_id, x.task_claimed_user AS assigner
      FROM wfl_task x
      JOIN (SELECT transaction_id, MAX(task_id) mid FROM wfl_task WHERE checkpoint_id = 17 GROUP BY transaction_id) m
        ON m.transaction_id = x.transaction_id AND m.mid = x.task_id) c17
  ON c17.transaction_id = ct.transaction_id
WHERE ct.task_current = 1 AND ct.checkpoint_id = 19 AND ct.task_status = 8
  AND c17.assigner IS NOT NULL AND ct.task_claimed_user <> c17.assigner;
