function ModalSpaceType() {
  const className = 'ModalSpaceType';
  let self = this;
  let spaceTypeId = '';
  let rowRefresh = '';
  let classFrom;

  this.init = function(){
    const vData = [
      { field_id:'txtMstName', type:'text', name:'Type Name', validator:{ notEmpty:true, maxLength:150 } },
      { field_id:'txaMstDesc', type:'text', name:'Description', validator:{ maxLength:255 } },
      { field_id:'chkMstStatus', type:'checkSingle', name:'Status', validator:{} }
    ];
    const formValidate = new MzValidate('formMst'); formValidate.registerFields(vData);
    $('#formMst').on('keyup change', function(){ $('#btnMstSubmit').attr('disabled', !formValidate.validateForm()); });
    $('#modal_space_type').on('hidden.bs.modal', function(){ formValidate.clearValidation(); $('#btnMstSubmit').attr('disabled', true); });
  $('#btnMstSubmit').on('click', function(){ ShowLoader(); setTimeout(function(){ try { if(!formValidate.validateForm()){ toastr['error'](_ALERT_MSG_VALIDATION,_ALERT_TITLE_ERROR); } else { const name=$('#txtMstName').val(); const desc=$('#txaMstDesc').val(); const status=$("input[name='chkMstStatus']").is(":checked") ? 1 : 0; const catId = $('#optMstCategoryId').val(); if (!catId) { toastr['error']('Please choose a Category for this Type', _ALERT_TITLE_ERROR); HideLoader(); return; } const data={ spaceCategoryId: parseInt(catId), spaceTypeName:name, spaceTypeDesc:desc, spaceTypeStatus:status }; if (spaceTypeId===''){ const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_type.php', method:'POST', data: JSON.stringify(data), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ spaceTypeId=resp.result.spaceTypeId; if (classFrom.getClassName()==='MainSpaceType'){ classFrom.addTableAct(resp.result);} $('#modal_space_type').modal('hide'); toastr['success'](resp.errmsg||'Created', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR); }); } else { const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_type.php/'+spaceTypeId, method:'PUT', data: JSON.stringify(data), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ if (classFrom.getClassName()==='MainSpaceType'){ classFrom.updateTableAct(resp.result, rowRefresh);} $('#modal_space_type').modal('hide'); toastr['success'](resp.errmsg||'Updated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR); }); } } } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 150); });
  };

  this.add = function(){ spaceTypeId=''; rowRefresh=''; ShowLoader(); setTimeout(function(){ try { mzSetFieldValue('MstStatus','1','checkSingle','1'); mzSetFieldValue('MstName','', 'text'); mzSetFieldValue('MstDesc','', 'textarea'); $('#lblMstTitle').html('<i class="fas fa-plus text-white"></i> &nbsp;Add Space Type'); $('#modal_space_type').modal({backdrop:'static', keyboard:false}); } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };
  // populate categories for add
  this.add = function(){ spaceTypeId=''; rowRefresh=''; ShowLoader(); setTimeout(function(){ try { mzSetFieldValue('MstStatus','1','checkSingle','1'); mzSetFieldValue('MstName','', 'text'); mzSetFieldValue('MstDesc','', 'textarea'); const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_category.php?status=1', method:'GET', dataType:'json', headers}).done(function(resp){ const $cat=$('#optMstCategoryId'); $cat.empty().append('<option value="" selected>Choose Category</option>'); (resp.result||[]).forEach(function(r){ $cat.append('<option value="'+r.spaceCategoryId+'">'+r.spaceCategoryName+'</option>'); }); $cat.materialSelect(); $('#lblMstTitle').html('<i class="fas fa-plus text-white"></i> &nbsp;Add Space Type'); $('#modal_space_type').modal({backdrop:'static', keyboard:false}); }); } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };

  this.edit = function(_id, _row){ ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id,_row]); spaceTypeId=_id; rowRefresh=_row; const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; // load categories then item
      $.ajax({ url:'api/ref_space_category.php?status=1', method:'GET', dataType:'json', headers}).done(function(respCats){ const $cat=$('#optMstCategoryId'); $cat.empty().append('<option value="" selected>Choose Category</option>'); (respCats.result||[]).forEach(function(r){ $cat.append('<option value="'+r.spaceCategoryId+'">'+r.spaceCategoryName+'</option>'); }); $cat.materialSelect();
        $.ajax({ url:'api/ref_space_type.php/'+spaceTypeId, method:'GET', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ const d=resp.result; mzSetFieldValue('MstName', d.spaceTypeName, 'text'); mzSetFieldValue('MstDesc', d.spaceTypeDesc, 'textarea'); mzSetFieldValue('MstStatus', d.spaceTypeStatus ? '1':'2', 'checkSingle', '1'); mzSetFieldValue('MstCategoryId', d.spaceCategoryId, 'select', 'Category *'); $('#lblMstTitle').html('<i class="far fa-edit text-white"></i> &nbsp;Edit Space Type'); $('#modal_space_type').modal({backdrop:'static', keyboard:false}); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} });
      });
    } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };

  this.deactivate = function(_id, _row){ ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id,_row]); const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_type.php/'+_id, method:'PUT', data: JSON.stringify({ spaceTypeStatus:0 }), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ if (classFrom.getClassName()==='MainSpaceType'){ classFrom.updateTableAct({spaceTypeStatus:0}, _row);} toastr['success'](resp.errmsg||'Deactivated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };

  this.activate = function(_id, _row){ ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id,_row]); const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_type.php/'+_id, method:'PUT', data: JSON.stringify({ spaceTypeStatus:1 }), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ if (classFrom.getClassName()==='MainSpaceType'){ classFrom.updateTableAct({spaceTypeStatus:1}, _row);} toastr['success'](resp.errmsg||'Activated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };

  this.delete = function(_id){ ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id]); const token=sessionStorage.getItem('token'); const headers= token?{'Authorization':'Bearer '+token}:{ }; $.ajax({ url:'api/ref_space_type.php/'+_id, method:'DELETE', dataType:'json', headers}).done(function(resp){ if(resp&&resp.success){ if (classFrom.getClassName()==='MainSpaceType'){ classFrom.genTable(1);} toastr['success'](resp.errmsg||'Deleted', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT,_ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message,_ALERT_TITLE_ERROR);} HideLoader(); }, 120); };

  this.getClassName = function(){ return className; };
  this.setClassFrom = function (_classFrom){ classFrom = _classFrom; };
}
