function ModalSpaceCategory() {

  const className = 'ModalSpaceCategory';
  let self = this;
  let spaceCategoryId = '';
  let rowRefresh = '';
  let classFrom;

  this.init = function () {
    const vData = [
      { field_id: 'txtMscName', type: 'text', name: 'Category Name', validator: { notEmpty: true, maxLength: 150 } },
      { field_id: 'txaMscDesc', type: 'text', name: 'Description', validator: { maxLength: 255 } },
      { field_id: 'chkMscStatus', type: 'checkSingle', name: 'Status', validator: {}},
    ];
    const formValidate = new MzValidate('formMsc');
    formValidate.registerFields(vData);
    $('#formMsc').on('keyup change', function(){ $('#btnMscSubmit').attr('disabled', !formValidate.validateForm()); });
    $('#modal_space_category').on('hidden.bs.modal', function(){ formValidate.clearValidation(); $('#btnMscSubmit').attr('disabled', true); });
    $('#btnMscSubmit').on('click', function(){ ShowLoader(); setTimeout(function(){ try { if (!formValidate.validateForm()) { toastr['error'](_ALERT_MSG_VALIDATION, _ALERT_TITLE_ERROR); } else { const name=$('#txtMscName').val(); const desc=$('#txaMscDesc').val(); const status=$("input[name='chkMscStatus']").is(":checked") ? 1 : 0; const data={ spaceCategoryName:name, spaceCategoryDesc:desc, spaceCategoryStatus:status }; let tempRow={}; if (spaceCategoryId==='') { const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php', method:'POST', data:data, dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ spaceCategoryId = resp.result.spaceCategoryId; if (classFrom.getClassName()==='MainSpaceCategory'){ tempRow = resp.result; classFrom.addTableAct(tempRow);} $('#modal_space_category').modal('hide'); toastr['success'](resp.errmsg||'Created', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(j){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } else { const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php/'+spaceCategoryId, method:'PUT', data: JSON.stringify(data), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ if (classFrom.getClassName()==='MainSpaceCategory'){ classFrom.updateTableAct(resp.result, rowRefresh);} $('#modal_space_category').modal('hide'); toastr['success'](resp.errmsg||'Updated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } } } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 200); });
  };

  this.add = function () { spaceCategoryId=''; rowRefresh=''; ShowLoader(); setTimeout(function(){ try { mzSetFieldValue('MscStatus', '1', 'checkSingle', '1'); mzSetFieldValue('MscName','', 'text'); mzSetFieldValue('MscDesc','', 'textarea'); $('#lblMscTitle').html('<i class="fas fa-plus text-white"></i> &nbsp;Add Space Category'); $('#modal_space_category').modal({backdrop:'static', keyboard:false}); } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 150); };

  this.edit = function (_id, _row) { ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id, _row]); spaceCategoryId=_id; rowRefresh=_row; const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php/'+spaceCategoryId, method:'GET', dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ const d=resp.result; mzSetFieldValue('MscName', d.spaceCategoryName, 'text'); mzSetFieldValue('MscDesc', d.spaceCategoryDesc, 'textarea'); mzSetFieldValue('MscStatus', d.spaceCategoryStatus ? '1':'2', 'checkSingle', '1'); $('#lblMscTitle').html('<i class="far fa-edit text-white"></i> &nbsp;Edit Space Category'); $('#modal_space_category').modal({backdrop:'static', keyboard:false}); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 150); };

  this.deactivate = function (_id, _row) { ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id, _row]); const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php/'+_id, method:'PUT', data: JSON.stringify({ spaceCategoryStatus:0 }), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ if (classFrom.getClassName()==='MainSpaceCategory'){ classFrom.updateTableAct({spaceCategoryStatus:0}, _row); } toastr['success'](resp.errmsg||'Deactivated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 150); };

  this.activate = function (_id, _row) { ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id, _row]); const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php/'+_id, method:'PUT', data: JSON.stringify({ spaceCategoryStatus:1 }), contentType:'application/json', dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ if (classFrom.getClassName()==='MainSpaceCategory'){ classFrom.updateTableAct({spaceCategoryStatus:1}, _row); } toastr['success'](resp.errmsg||'Activated', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 150); };

  this.delete = function (_id) { ShowLoader(); setTimeout(function(){ try { mzCheckFuncParam([_id]); const token = sessionStorage.getItem('token'); const headers = token ? { 'Authorization':'Bearer '+token } : {}; $.ajax({ url:'api/ref_space_category.php/'+_id, method:'DELETE', dataType:'json', headers}).done(function(resp){ if(resp && resp.success){ if (classFrom.getClassName()==='MainSpaceCategory'){ classFrom.genTableAct(1);} toastr['success'](resp.errmsg||'Deleted', _ALERT_TITLE_SUCCESS); } else { toastr['error']((resp&&resp.errmsg)||_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR);} }).fail(function(){ toastr['error'](_ALERT_MSG_ERROR_DEFAULT, _ALERT_TITLE_ERROR); }); } catch(e){ toastr['error'](e.message, _ALERT_TITLE_ERROR);} HideLoader(); }, 150); };

  this.getClassName = function(){ return className; };
  this.setClassFrom = function (_classFrom){ classFrom = _classFrom; };
}
