; this is an INI file
[database]
;username = root
username = zaid
;password = password
password = Amlyda@1982
;password = Globalfm@19
dbhost = localhost
dbname = gems
;dbhost = 10.101.11.71
;log_dir = /Applications/XAMPP/logs/gems
;log_dir = ../../../../logs/gems
log_dir = ../../logs/gems.metadatasystem.my
environment = linux