; this is an INI file
[database]
username = root
password = password
;dbname = gems_clean
dbhost = localhost
;log_dir = ../../../../logs/gems
;password = Globalfm@19
dbname = gems
;dbhost = 10.101.11.71
log_dir = ../../logs/gems
environment = windows