; this is an INI file
[database]
;username = root
;password = password
;dbname = gems_clean
;dbhost = localhost
username = metadata_zaid
password = Amlyd654987
dbname = metadata_gems
dbhost = gems2.metadatasyst.com
log_dir = ../../../../logs/gems
environment = windows
