; this is an INI file
[database]
username = root
;password = password
password = Globalfm@19
;dbhost = www.metadatasystem.my
dbname = gems2
dbhost = 10.101.11.69
>>>>>>> Stashed changes
;log_dir = /Applications/XAMPP/logs/gems
;log_dir = ../../../../logs/gems2
log_dir = C:\xampp\htdocs\maintenance\logs
environment = windows